### PR TITLE
Remove explicit optimization settings for targets

### PR DESCRIPTION
**Pull request by GarthSnyder**
Swift has been going through some changes in string implementation lately, so I checked performance on Xcode 12 beta and Swift 5.3. Everything seems to be stable; no updates needed.

However, I noticed that every target in the Xcode project has its optimization for the Release build set to "none". Is this intentional? I'm not 100% sure of this, but I believe that if you just use the package normally through Carthage or SPM, you get the regular Release build. And SwiftSoup benefits greatly from optimization.

This PR just deletes all the target-specific optimization settings and lets them inherit from the top-level project, where they are -Ospeed and -Onone for Release and Debug, respectively.

### CODE REVIEW

**Comment by scinfu** [comment]
It's an old fix for xcode 11 bug.

**Comment by jbrayton** [comment]
I use SwiftSoup with Carthage. Incorporating this pull request resulted in a significant performance improvement for my app, [Unread](https://www.goldenhillsoftware.com/unread/). Thank you!

The pull request works well with Xcode 11.5, but it appears to trigger this compilation error on the first Xcode 12 beta:

```
Undefined symbols for architecture armv7:
  "type metadata for Swift._StringObject.Variant", referenced from:
      outlined init with take of Swift._StringObject.Variant in CharacterReader.o
```

Based on [this thread](https://developer.apple.com/forums/thread/649918) it looks like the issue is specific to compiling for 32-bit iOS devices. I was able to avoid it by bumping the deployment target to iOS 11. 

I do not know if the compilation issue will be fixed in a subsequent version of Xcode or if bumping the deployment target is the right move for the SwiftSoup framework, but feel free to incorporate [that commit](https://github.com/jbrayton/SwiftSoup/commit/766d1020c95b5904af7bc59f449d691bb1ff5e04) into this pull request if you want it.

**Comment by scinfu** [comment]
thank you
