### ISSUE TITLE
SwiftSoup 2.8.1 doesn't work in Linux

### ISSUE THREAD

**Issue by kevinrenskers** [scinfu/SwiftSoup#298]
I have a project that uses SwiftSoup, and it builds on Netlify Ising Ubuntu 24.04. After updating to SwiftSoup 2.8.1 my project fails to build with the following error:

```
error: emit-module command failed with exit code 1 (use -v to see invocation) (https://ntl.fyi/exit-code-1)
[25/113] Emitting module SwiftSoup
/opt/build/repo/.build/checkouts/SwiftSoup/Sources/String.swift:285:34: error: cannot find type 'UTF8Char' in scope
|     }
|
|     func utf8CharAt(_ i: Int) -> UTF8Char {
|                                  `- error: cannot find type 'UTF8Char' in scope
|       return self.utf8Array[i]
|     }
```

**Comment by mergesort** [comment]
I wanted to +1 this, since I came across the same issue this morning when trying to deploy my Swift app to Heroku. It appears to be tied to #296, which seems like a useful fix, but should be made in a Linux-compatible manner.

Thank you so much!

**Comment by aehlke** [comment]
I will be able to look into this later - meanwhile please let me know if you can contribute a fix or explain how this can be fixed. Test coverage is also highly appreciated

cc @amyworrall

**Comment by aehlke** [comment]
Fixed in https://github.com/scinfu/SwiftSoup/pull/299

**Comment by aehlke** [comment]
btw @mergesort your work is awesome! just started using boutique. thanks so much

**Comment by mergesort** [comment]
Thank you so much for the quick fix, it was no problem at all! And thank you very much for the kind words — hope you like Boutique! 🙇🏻‍♂️
