### ISSUE TITLE
How to manage SwiftSoup by Carthage?  It builds failed.

### ISSUE THREAD

**Issue by CSwater2016** [scinfu/SwiftSoup#29]
`SwiftSoup` scheme builds well in the project.
However ,  when I try to manage it in Carthage , it builds failed .

I'am no sure which cause this error , the project itself or the Carthage?

Following is some of the  the error message logged by Carthage, I hope you can give me some suggestion.

Xcode 8.2.1 (8C1002)
Swift 3.0.2
Carthage 0.23
SwiftSoup tag 1.4.2

```
Undefined symbols for architecture arm64:
  "_FE9SwiftSoupScG9AmpersandSc", referenced from:
      function signature specialization <Arg[0] = Owned To Guaranteed> of SwiftSoup.TokeniserState.read (SwiftSoup.Tokeniser, SwiftSoup.CharacterReader) throws -> () in TokeniserState.o
  "_FE9SwiftSoupScG10BackslashFSc", referenced from:
      function signature specialization <Arg[0] = Owned To Guaranteed> of SwiftSoup.TokeniserState.read (SwiftSoup.Tokeniser, SwiftSoup.CharacterReader) throws -> () in TokeniserState.o
  "_FE9SwiftSoupScG8LessThanSc", referenced from:
      function signature specialization <Arg[0] = Owned To Guaranteed> of SwiftSoup.TokeniserState.read (SwiftSoup.Tokeniser, SwiftSoup.CharacterReader) throws -> () in TokeniserState.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Ld /Users/umisky/Library/Caches/org.carthage.CarthageKit/DerivedData/SwiftSoup/1.2.9/Build/Intermediates/SwiftSoup.build/Release-iphoneos/SwiftSoup.build/Objects-normal/armv7/SwiftSoup normal armv7
    cd /Users/umisky/Desktop/Reimu/Carthage/Checkouts/SwiftSoup
    export IPHONEOS_DEPLOYMENT_TARGET=9.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch armv7 -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.2.sdk -L/Users/umisky/Library/Caches/org.carthage.CarthageKit/DerivedData/SwiftSoup/1.2.9/Build/Products/Release-iphoneos -F/Users/umisky/Library/Caches/org.carthage.CarthageKit/DerivedData/SwiftSoup/1.2.9/Build/Products/Release-iphoneos -filelist /Users/umisky/Library/Caches/org.carthage.CarthageKit/DerivedData/SwiftSoup/1.2.9/Build/Intermediates/SwiftSoup.build/Release-iphoneos/SwiftSoup.build/Objects-normal/armv7/SwiftSoup.LinkFileList -install_name @rpath/SwiftSoup.framework/SwiftSoup -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -miphoneos-version-min=9.0 -dead_strip -Xlinker -object_path_lto -Xlinker /Users/umisky/Library/Caches/org.carthage.CarthageKit/DerivedData/SwiftSoup/1.2.9/Build/Intermediates/SwiftSoup.build/Release-iphoneos/SwiftSoup.build/Objects-normal/armv7/SwiftSoup_lto.o -fembed-bitcode -Xlinker -bitcode_verify -Xlinker -bitcode_hide_symbols -Xlinker -bitcode_symbol_map -Xlinker /Users/umisky/Library/Caches/org.carthage.CarthageKit/DerivedData/SwiftSoup/1.2.9/Build/Products/Release-iphoneos -fobjc-link-runtime -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos -Xlinker -add_ast_path -Xlinker /Users/umisky/Library/Caches/org.carthage.CarthageKit/DerivedData/SwiftSoup/1.2.9/Build/Intermediates/SwiftSoup.build/Release-iphoneos/SwiftSoup.build/Objects-normal/armv7/SwiftSoup.swiftmodule -single_module -compatibility_version 1 -current_version 1 -Xlinker -dependency_info -Xlinker /Users/umisky/Library/Caches/org.carthage.CarthageKit/DerivedData/SwiftSoup/1.2.9/Build/Intermediates/SwiftSoup.build/Release-iphoneos/SwiftSoup.build/Objects-normal/armv7/SwiftSoup_dependency_info.dat -o /Users/umisky/Library/Caches/org.carthage.CarthageKit/DerivedData/SwiftSoup/1.2.9/Build/Intermediates/SwiftSoup.build/Release-iphoneos/SwiftSoup.build/Objects-normal/armv7/SwiftSoup
Undefined symbols for architecture armv7:
  "_FE9SwiftSoupScG9AmpersandSc", referenced from:
      function signature specialization <Arg[0] = Owned To Guaranteed> of SwiftSoup.TokeniserState.read (SwiftSoup.Tokeniser, SwiftSoup.CharacterReader) throws -> () in TokeniserState.o
  "_FE9SwiftSoupScG8LessThanSc", referenced from:
      function signature specialization <Arg[0] = Owned To Guaranteed> of SwiftSoup.TokeniserState.read (SwiftSoup.Tokeniser, SwiftSoup.CharacterReader) throws -> () in TokeniserState.o
ld: symbol(s) not found for architecture armv7

** BUILD FAILED **


The following build commands failed:
	Ld /Users/umisky/Library/Caches/org.carthage.CarthageKit/DerivedData/SwiftSoup/1.2.9/Build/Intermediates/SwiftSoup.build/Release-iphoneos/SwiftSoup.build/Objects-normal/arm64/SwiftSoup normal arm64
(1 failure)
```

**Comment by scinfu** [comment]
Hi,
Check last versione 1.5.1

**Comment by CSwater2016** [comment]
“Use Legacy Swift Language Version”
It seems to be problems with swift version, It works in Xcode 9.0 with Swift 4.0 and failed on Xcode 8.2.1 with Swift 3.02.

I try to fix the compile error, but failed. Maybe I should upgrade the Xcode right now.

**Comment by scinfu** [comment]
The problem is the file .swift-version that is 4.0, I can't regress it 3.
You can try to download the master branch, change it and compile. It's not a good and easy solution.
If some one have a better solution for multiple compatibility we can discuss it.

Thank you
